package com.dong.persistence.dao;

import com.dong.persistence.entity.Client;

/**
 * @author XuDong, Zhu
 * @version 2.4.2
 * @ClassName: ClientMapper
 * @Description: (这里用一句话描述这个类的作用)
 * @date 2017 -02-22 16:19:32
 */
public interface ClientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_client
     *
     * @param id the id
     * @return int
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:32
     * @version 2.4.2
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_client
     *
     * @param record the record
     * @return int
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:32
     * @version 2.4.2
     * @mbggenerated
     */
    int insert(Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_client
     *
     * @param record the record
     * @return int
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:32
     * @version 2.4.2
     * @mbggenerated
     */
    int insertSelective(Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_client
     *
     * @param id the id
     * @return client
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:32
     * @version 2.4.2
     * @mbggenerated
     */
    Client selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_client
     *
     * @param record the record
     * @return int
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:32
     * @version 2.4.2
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth2_client
     *
     * @param record the record
     * @return int
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:32
     * @version 2.4.2
     * @mbggenerated
     */
    int updateByPrimaryKey(Client record);
}