package com.dong.persistence.dao;

import com.dong.persistence.entity.Organization;

/**
 * @author XuDong, Zhu
 * @version 2.4.2
 * @ClassName: OrganizationMapper
 * @Description: (这里用一句话描述这个类的作用)
 * @date 2017 -02-22 16:19:33
 */
public interface OrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @param id the id
     * @return int
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @param record the record
     * @return int
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    int insert(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @param record the record
     * @return int
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    int insertSelective(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @param id the id
     * @return organization
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    Organization selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @param record the record
     * @return int
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @param record the record
     * @return int
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    int updateByPrimaryKey(Organization record);
}