package com.dong.persistence.dao;

import com.dong.persistence.entity.Resource;

/**
 * @author XuDong, Zhu
 * @version 2.4.2
 * @ClassName: ResourceMapper
 * @Description: (这里用一句话描述这个类的作用)
 * @date 2017 -02-22 16:19:33
 */
public interface ResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @param id the id
     * @return int
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @param record the record
     * @return int
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    int insert(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @param record the record
     * @return int
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    int insertSelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @param id the id
     * @return resource
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    Resource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @param record the record
     * @return int
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @param record the record
     * @return int
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    int updateByPrimaryKey(Resource record);
}