package com.dong.persistence.dao;

import com.dong.persistence.entity.User;

/**
 * @author XuDong, Zhu
 * @version 2.4.2
 * @ClassName: UserMapper
 * @Description: (这里用一句话描述这个类的作用)
 * @date 2017 -02-22 16:19:32
 */
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @param id the id
     * @return int
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:32
     * @version 2.4.2
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @param record the record
     * @return int
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:32
     * @version 2.4.2
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @param record the record
     * @return int
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:32
     * @version 2.4.2
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @param id the id
     * @return user
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:32
     * @version 2.4.2
     * @mbggenerated
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @param record the record
     * @return int
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:32
     * @version 2.4.2
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @param record the record
     * @return int
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:32
     * @version 2.4.2
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);
}