package com.dong.persistence.dao;

import com.dong.persistence.entity.UserRunAsKey;

/**
 * @author XuDong, Zhu
 * @version 2.4.2
 * @ClassName: UserRunAsMapper
 * @Description: (这里用一句话描述这个类的作用)
 * @date 2017 -02-22 16:19:33
 */
public interface UserRunAsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_runas
     *
     * @param key the key
     * @return int
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    int deleteByPrimaryKey(UserRunAsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_runas
     *
     * @param record the record
     * @return int
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    int insert(UserRunAsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_runas
     *
     * @param record the record
     * @return int
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    int insertSelective(UserRunAsKey record);
}