package com.dong.persistence.entity;

/**
 * @author XuDong, Zhu
 * @version 2.4.2
 * @ClassName: Organization
 * @Description: (这里用一句话描述这个类的作用)
 * @date 2017 -02-22 16:19:34
 */
public class Organization {
    /**
     * 组织表主键
     */
    private Long id;

    /**
     * 组织机构名称
     */
    private String name;

    /**
     * 父级组织表主键
     */
    private Long parentId;

    /**
     * 父级组织表主键列表
     */
    private String parentIds;

    /**
     * 是否有效
     */
    private Boolean available;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.id
     *
     * @return the value of sys_organization.id
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:34
     * @version 2.4.2
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.id
     *
     * @param id the value for sys_organization.id
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:34
     * @version 2.4.2
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.name
     *
     * @return the value of sys_organization.name
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:34
     * @version 2.4.2
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.name
     *
     * @param name the value for sys_organization.name
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:34
     * @version 2.4.2
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.parent_id
     *
     * @return the value of sys_organization.parent_id
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:34
     * @version 2.4.2
     * @mbggenerated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.parent_id
     *
     * @param parentId the value for sys_organization.parent_id
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:34
     * @version 2.4.2
     * @mbggenerated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.parent_ids
     *
     * @return the value of sys_organization.parent_ids
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:34
     * @version 2.4.2
     * @mbggenerated
     */
    public String getParentIds() {
        return parentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.parent_ids
     *
     * @param parentIds the value for sys_organization.parent_ids
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:34
     * @version 2.4.2
     * @mbggenerated
     */
    public void setParentIds(String parentIds) {
        this.parentIds = parentIds == null ? null : parentIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.available
     *
     * @return the value of sys_organization.available
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:34
     * @version 2.4.2
     * @mbggenerated
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.available
     *
     * @param available the value for sys_organization.available
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:35
     * @version 2.4.2
     * @mbggenerated
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }
}