package com.dong.persistence.entity;

/**
 * @author XuDong, Zhu
 * @version 2.4.2
 * @ClassName: Resource
 * @Description: (这里用一句话描述这个类的作用)
 * @date 2017 -02-22 16:19:34
 */
public class Resource {
    /**
     * 资源表主键
     */
    private Long id;

    /**
     * 资源名称
     */
    private String name;

    /**
     * 资源类型
     */
    private String type;

    /**
     * 资源路径
     */
    private String url;

    /**
     * 父级资源表主键
     */
    private Long parentId;

    /**
     * 父级资源表主键列表
     */
    private String parentIds;

    /**
     * 权限字符串
     */
    private String permission;

    /**
     * 是否有效
     */
    private Boolean available;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.id
     *
     * @return the value of sys_resource.id
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:34
     * @version 2.4.2
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.id
     *
     * @param id the value for sys_resource.id
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:34
     * @version 2.4.2
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.name
     *
     * @return the value of sys_resource.name
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:34
     * @version 2.4.2
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.name
     *
     * @param name the value for sys_resource.name
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:34
     * @version 2.4.2
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.type
     *
     * @return the value of sys_resource.type
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:34
     * @version 2.4.2
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.type
     *
     * @param type the value for sys_resource.type
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:34
     * @version 2.4.2
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.url
     *
     * @return the value of sys_resource.url
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:34
     * @version 2.4.2
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.url
     *
     * @param url the value for sys_resource.url
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:34
     * @version 2.4.2
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.parent_id
     *
     * @return the value of sys_resource.parent_id
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:34
     * @version 2.4.2
     * @mbggenerated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.parent_id
     *
     * @param parentId the value for sys_resource.parent_id
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:34
     * @version 2.4.2
     * @mbggenerated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.parent_ids
     *
     * @return the value of sys_resource.parent_ids
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:34
     * @version 2.4.2
     * @mbggenerated
     */
    public String getParentIds() {
        return parentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.parent_ids
     *
     * @param parentIds the value for sys_resource.parent_ids
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:34
     * @version 2.4.2
     * @mbggenerated
     */
    public void setParentIds(String parentIds) {
        this.parentIds = parentIds == null ? null : parentIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.permission
     *
     * @return the value of sys_resource.permission
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:34
     * @version 2.4.2
     * @mbggenerated
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.permission
     *
     * @param permission the value for sys_resource.permission
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:34
     * @version 2.4.2
     * @mbggenerated
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.available
     *
     * @return the value of sys_resource.available
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:34
     * @version 2.4.2
     * @mbggenerated
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.available
     *
     * @param available the value for sys_resource.available
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:34
     * @version 2.4.2
     * @mbggenerated
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }
}