package com.dong.persistence.entity;

/**
 * @author XuDong, Zhu
 * @version 2.4.2
 * @ClassName: User
 * @Description: (这里用一句话描述这个类的作用)
 * @date 2017 -02-22 16:19:33
 */
public class User {
    /**
     * 用户表主键
     */
    private Long id;

    /**
     * 用户所属组织表主键
     */
    private Long organizationId;

    /**
     * 用户名
     */
    private String username;

    /**
     * 密码
     */
    private String password;

    /**
     * 加密串（盐）
     */
    private String salt;

    /**
     * 用户拥有的角色列表
     */
    private String roleIds;

    /**
     * 是否被锁
     */
    private Boolean locked;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.id
     *
     * @return the value of sys_user.id
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.id
     *
     * @param id the value for sys_user.id
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.organization_id
     *
     * @return the value of sys_user.organization_id
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    public Long getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.organization_id
     *
     * @param organizationId the value for sys_user.organization_id
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    public void setOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.username
     *
     * @return the value of sys_user.username
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.username
     *
     * @param username the value for sys_user.username
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.password
     *
     * @return the value of sys_user.password
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.password
     *
     * @param password the value for sys_user.password
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.salt
     *
     * @return the value of sys_user.salt
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.salt
     *
     * @param salt the value for sys_user.salt
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.role_ids
     *
     * @return the value of sys_user.role_ids
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    public String getRoleIds() {
        return roleIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.role_ids
     *
     * @param roleIds the value for sys_user.role_ids
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    public void setRoleIds(String roleIds) {
        this.roleIds = roleIds == null ? null : roleIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.locked
     *
     * @return the value of sys_user.locked
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    public Boolean getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.locked
     *
     * @param locked the value for sys_user.locked
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:33
     * @version 2.4.2
     * @mbggenerated
     */
    public void setLocked(Boolean locked) {
        this.locked = locked;
    }

    /**
     * To string.
     *
     * @return string
     * @author XuDong, Zhu
     * @date 2017 -02-22 17:00:44
     * @version 2.4.2
     */
    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer("User{");
        sb.append("id=").append(id);
        sb.append(", organizationId=").append(organizationId);
        sb.append(", username='").append(username).append('\'');
        sb.append(", password='").append(password).append('\'');
        sb.append(", salt='").append(salt).append('\'');
        sb.append(", roleIds='").append(roleIds).append('\'');
        sb.append(", locked=").append(locked);
        sb.append('}');
        return sb.toString();
    }
}