package com.dong.persistence.entity;

/**
 * @author XuDong, Zhu
 * @version 2.4.2
 * @ClassName: UserRunAsKey
 * @Description: (这里用一句话描述这个类的作用)
 * @date 2017 -02-22 16:19:35
 */
public class UserRunAsKey {
    /**
     * 权限提供者
     */
    private Long fromUserId;

    /**
     * 权限授予者
     */
    private Long toUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_runas.from_user_id
     *
     * @return the value of sys_user_runas.from_user_id
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:35
     * @version 2.4.2
     * @mbggenerated
     */
    public Long getFromUserId() {
        return fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_runas.from_user_id
     *
     * @param fromUserId the value for sys_user_runas.from_user_id
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:35
     * @version 2.4.2
     * @mbggenerated
     */
    public void setFromUserId(Long fromUserId) {
        this.fromUserId = fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_runas.to_user_id
     *
     * @return the value of sys_user_runas.to_user_id
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:35
     * @version 2.4.2
     * @mbggenerated
     */
    public Long getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_runas.to_user_id
     *
     * @param toUserId the value for sys_user_runas.to_user_id
     * @author XuDong, Zhu
     * @date 2017 -02-22 16:19:35
     * @version 2.4.2
     * @mbggenerated
     */
    public void setToUserId(Long toUserId) {
        this.toUserId = toUserId;
    }
}